### ISSUE TITLE
[app] Recipes doesn't get stored

### ISSUE THREAD

**Issue by cibersheep** [bhdouglass/recipe-boss#1]
Adding a recipe is loading forever and stores nothing -> apparmor allow local storage?
If you press cancel, you can see that there is a recipe but it does load. Restarting the app shows empty list.

1) New recipe
2) Fill title and tap save
- App is saving forever
log: ([js] file://[...]index.html#new:0) Uncaught (in promise) [object Object]

3) Tap cancel (you can see the title of the recipe)
4) Tap on title
recipe is loading for ever
log: [js] file[...]static/js/vendor.[...].js:1 TypeError: Cannot read property 'image' of undefined

5) Restart app
6) list of recipes is empty

**Comment by bhdouglass** [comment]
This has been fixed in the website and v0.1.2 of the app!
