### ISSUE TITLE
[web][app] Widget covers top area / hides logout on small screens

### ISSUE THREAD

**Issue by cibersheep** [bhdouglass/recipe-boss#4]
Widget covers add recipe, title, etc.
![imatge](https://user-images.githubusercontent.com/6640041/35569752-4c211e62-05cd-11e8-9a21-ae7ca3b5908d.png)

Logout is not visible
![imatge](https://user-images.githubusercontent.com/6640041/35569882-c3f31a9e-05cd-11e8-82b9-794756eb81fe.png)

**Comment by bhdouglass** [comment]
Fixed on the website & and in v0.1.3 of the app.
